packages:
  - packages/*

catalog:
  "@types/node": ^24.10.0
  "@vitejs/plugin-vue": ^6.0.1
  "@vue/tsconfig": ^0.8.1
  typescript: ^5.9.3
  vite: 7.2.2
  vue: ^3.5.24
  vue-tsc: ^3.1.3
  vitest: ^4.0.8
